name: Deploy Static Site to GitHub Pages

on:
  push:
    branches:
      - main # change if your branch is master

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup GitHub Pages
        uses: actions/configure-pages@v4

      - name: Upload static files
        uses: actions/upload-pages-artifact@v3
        with:
          path: . # uploads entire repo (index.html must be in root)

      - name: Deploy
        uses: actions/deploy-pages@v4
